sudo: false
language: scala
scala:
  - 2.11.8
env:
  global:
    - OWNER=alg-owner
    - ALGORITHM_NAME=concise-alg-name
    - ALGORITHMIA_USER=travis
    - ES_ALGORITHMIA_API_ADDRESS=algo-url
    - ES_ALGORITHM_DESCRIPTOR=$OWNER/$ALGORITHM_NAME/$TRAVIS_COMMIT
script:
  - sbt ++$TRAVIS_SCALA_VERSION test
jdk:
  - oraclejdk8
deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh -a $ALGORITHM_NAME -u $ALGORITHMIA_USER -p $ALGORITHMIA_PASSWORD
    on:
      branch: master
      tags: false
  - provider: script
    skip_cleanup: true
    script: bash scripts/publish.sh -a $ALGORITHM_NAME -k $ES_ALGORITHMIA_API_KEY -t $TRAVIS_TAG -g $TRAVIS_REPO_SLUG
    on:
      branch: master
      tags: true
after_deploy:
  - echo "Testing deployed endpoint"
  - sbt ++$TRAVIS_SCALA_VERSION it:test
